version: '2'

services:
  database:
    container_name: sms-db
    image: "${DOCKER_ID}pixelkube-sms-db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=pixelkube 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: